### ISSUE TITLE
后台

### ISSUE THREAD

**Issue by otldan** [huangruiLearn/flutter_hrlweibo#1]
您好，可以分享份后台源码吗？谢谢

**Comment by binbin0915** [comment]
同求 省得自己根据JSON反推了 楼主界面写的不错 赞下~
  static const baseUrl ='http://212.64.95.5:8080/hrlweibo/';

**Comment by huangruiLearn** [comment]
过一段吧 我会联连同sql文件 把后台源码一块开源出来

**Comment by chenyx886** [comment]
您好，可以分享份后台源码吗？谢谢

**Comment by chenyx886** [comment]
请你的后台是使用什么语言开发的呢？

**Comment by huangruiLearn** [comment]
> 请你的后台是使用什么语言开发的呢？

Java+mysql 我整理下代码 过段时间就发出来
