### ISSUE TITLE
我这有个内容社区APP的需求，不知道你这边是否有时间和兴趣

### ISSUE THREAD

**Issue by yhanwen** [huangruiLearn/flutter_hrlweibo#11]
你好，刚看到你这个微博客户端的项目感觉做的很棒
我这手头上正好有个内容社区的事情，感觉你这大部分功能都能用上，不知道是否有兴趣
如果感兴趣的话咱们可以进一步沟通一下需求和价钱
谢谢~

**Comment by huangruiLearn** [comment]
@yhanwen    我弄不成, 你可以下载代码参考下
