### ISSUE TITLE
flutter_record_plugin plugin报错

### ISSUE THREAD

**Issue by stoneLee81** [huangruiLearn/flutter_hrlweibo#12]
ios 13.5
flutter 1.17.4
RecordButton widget的var recording = await FlutterRecordPlugin.stop();函数报错：
MissingPluginException(No implementation found for method hasPermissions on channel flutter_record_plugin)

**Comment by huangruiLearn** [comment]
@stoneLee81      你先把pubspec.yaml  里 flutter_record_plugin 地址换成他的试下  https://github.com/ZaraclaJ/audio_recorder
