### ISSUE TITLE
Android编译不通过

### ISSUE THREAD

**Issue by CodeDome** [huangruiLearn/flutter_hrlweibo#16]
运行以后报错，请问大神这是什么原因
`Launching lib/main.dart on sdk gphone x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve com.android.tools:dvlib:26.3.1.
     Required by:
         project : > com.android.tools.build:gradle:3.3.1 > com.android.tools.build:builder:3.3.1 > com.android.tools:sdklib:26.3.1
      > Could not resolve com.android.tools:dvlib:26.3.1.
         > Could not get resource 'https://maven.aliyun.com/repository/google/com/android/tools/dvlib/26.3.1/dvlib-26.3.1.pom'.
            > Could not GET 'https://maven.aliyun.com/repository/google/com/android/tools/dvlib/26.3.1/dvlib-26.3.1.pom'.
               > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 3m 37s
Exited (sigterm)
Exception: Gradle task assembleDebug failed with exit code 1
`

**Comment by huangruiLearn** [comment]
你网络问题吧 @CodeDome

**Comment by ljh1234** [comment]
挂个梯子试试？
