### ISSUE TITLE
跑不起来，大部分代码爆红，语法错误

### ISSUE THREAD

**Issue by jiangzhengnan** [huangruiLearn/flutter_hrlweibo#20]
跑不起来，大部分代码爆红，语法错误
flutter 1.20.2
dart 2.9.1
![image](https://user-images.githubusercontent.com/14868338/91439767-20bead80-e8a0-11ea-950b-55a4206525b1.png)

**Comment by PPAbner** [comment]
+1

**Comment by lianmi** [comment]
extended_nested_scroll_view的部件相关部分报错了，说找不到child ，希望代码适配一下最新的flutter

**Comment by conghuasijidan** [comment]
flutter 1.20.4 运行也是一堆报错，iOS 安卓 都跑不起来

**Comment by zoubihai** [comment]
+1

**Comment by lan2000** [comment]
flutter 1.22.5版本，出现以下问题

lib/routers/routers.dart:2:1: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:fluro/src/router.dart'.
import 'package:flutter_hrlweibo/public.dart';
^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-0.5.0/lib/src/extended_editable_text.dart:743:7: Error: The non-abstract class 'ExtendedEditableTextState' is missing implementations for these members:
 - TextInputClient.currentAutofillScope
 - TextInputClient.performPrivateCommand
 - TextInputClient.showAutocorrectionPromptRect
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ExtendedEditableTextState extends State<ExtendedEditableText>
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:804:22: Context: 'TextInputClient.currentAutofillScope' is defined here.
  AutofillScope? get currentAutofillScope;
                     ^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:813:8: Context: 'TextInputClient.performPrivateCommand' is defined here.
  void performPrivateCommand(String action, Map<String, dynamic> data);
       ^^^^^^^^^^^^^^^^^^^^^
../../../flutter/packages/flutter/lib/src/services/text_input.dart:822:8: Context: 'TextInputClient.showAutocorrectionPromptRect' is defined here.
  void showAutocorrectionPromptRect(int start, int end);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-0.5.3/lib/src/selection/material_text_selection_controls.dart:147:10: Error: The method 'ExtendedMaterialTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
  Widget buildToolbar(
         ^
../../../flutter/packages/flutter/lib/src/widgets/text_selection.dart:128:10: Context: This is the overridden method ('buildToolbar').
  Widget buildToolbar(
         ^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-0.5.3/lib/src/selection/cupertino_text_selection_controls.dart:317:10: Error: The method 'ExtendedCupertinoTextSelectionControls.buildToolbar' has fewer positional arguments than those of overridden method 'TextSelectionControls.buildToolbar'.
  Widget buildToolbar(
         ^
../../../flutter/packages/flutter/lib/src/widgets/text_selection.dart:128:10: Context: This is the overridden method ('buildToolbar').
  Widget buildToolbar(
         ^
lib/main.dart:27:20: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:fluro/src/router.dart'.
    final router = Router();
                   ^^^^^^
lib/pages/find/find_hot_search.dart:149:21: Error: No named parameter with the name 'child'.
                    child: SliverAppBar(
                    ^^^^^
../../../flutter/packages/flutter/lib/src/widgets/nested_scroll_view.dart:1727:9: Context: Found this candidate, but the arguments don't match.
  const SliverOverlapAbsorber({
        ^^^^^^^^^^^^^^^^^^^^^
lib/pages/mine/personinfo_page.dart:335:25: Error: No named parameter with the name 'child'.
                        child: SliverAppBar(
                        ^^^^^
../../../flutter/packages/flutter/lib/src/widgets/nested_scroll_view.dart:1727:9: Context: Found this candidate, but the arguments don't match.
  const SliverOverlapAbsorber({
        ^^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-0.5.0/lib/src/extended_editable_text.dart:1626:36: Error: Too few positional arguments: 2 required, 1 given.
        ? () => controls.handleCopy(this)
                                   ^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_field-0.5.0/lib/src/extended_editable_text.dart:1772:29: Error: Getter not found: 'obscuringCharacter'.
      text = RenderEditable.obscuringCharacter * text.length;
                            ^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-0.5.3/lib/src/selection/material_text_selection_controls.dart:187:59: Error: Too few positional arguments: 2 required, 1 given.
          handleCopy: canCopy(delegate) ? () => handleCopy(delegate) : null,
                                                          ^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-0.5.3/lib/src/selection/cupertino_text_selection_controls.dart:389:49: Error: The argument type 'void Function(TextSelectionDelegate, ClipboardStatusNotifier)' can't be assigned to the parameter type 'void Function(TextSelectionDelegate)'.
 - 'TextSelectionDelegate' is from 'package:flutter/src/services/text_input.dart' ('../../../flutter/packages/flutter/lib/src/services/text_input.dart').
 - 'ClipboardStatusNotifier' is from 'package:flutter/src/widgets/text_selection.dart' ('../../../flutter/packages/flutter/lib/src/widgets/text_selection.dart').
        localizations.copyButtonLabel, canCopy, handleCopy);
                                                ^
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/extended_text_library-0.5.3/lib/src/selection/extended_text_selection_overlay.dart:329:46: Error: Too few positional arguments: 7 required, 6 given.
        child: selectionControls.buildToolbar(
                                             ^

**Comment by wangfeng211** [comment]
+1，全都报红，都是错误

**Comment by ixugo** [comment]
+1

**Comment by hexbo** [comment]
https://github.com/fluttercandies/extended_text_field/issues/86

**Comment by jiangzhengnan** [comment]
为啥关了。。
