### ISSUE TITLE
我下载的项目运行不起来，报错如下，是因为我AS的版本太高了吗，3.6.3的

### ISSUE THREAD

**Issue by taozhixiang** [huangruiLearn/flutter_hrlweibo#3]
Compiler message:
/C:/soft/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.0/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/soft/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.0/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^

Compiler message:
/C:/soft/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.0/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/soft/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.0/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\soft\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 882

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\soft\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by flyouting** [comment]
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...

Compiler message:
../../../flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.1.0/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^

**Comment by ecenllen** [comment]
我的也是这个问题

**Comment by FKLam** [comment]
这个是flutter 版本不对导致的。改为相应的版本就行。

**Comment by hanqingkai** [comment]
我也一样这个问题，dio改成3.0就全红了， 不知道怎么搞

**Comment by huangruiLearn** [comment]
> 我也一样这个问题，dio改成3.0就全红了， 不知道怎么搞

flutter和dio改成1.17.1 和3.0.9了     还不行开上vpn试试
